"""Table definitions used by queries. The schema itself is owned by the Alembic migrations."""

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import TSVECTOR

from app.core.config import settings

metadata = sa.MetaData()

sources = sa.Table(
    "sources",
    metadata,
    sa.Column("id", sa.Text, primary_key=True),
    sa.Column("jurisdiction", sa.String(2), nullable=False),
    sa.Column("title", sa.Text, nullable=False),
    sa.Column("source_type", sa.Text, nullable=False),
    sa.Column("url", sa.Text),
    sa.Column("version_date", sa.Date),
    sa.Column("file_sha256", sa.String(64), nullable=False),
    sa.Column("ingested_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
)

chunks = sa.Table(
    "chunks",
    metadata,
    sa.Column("id", sa.Text, primary_key=True),
    sa.Column("source_id", sa.Text, sa.ForeignKey("sources.id", ondelete="CASCADE"), nullable=False),
    sa.Column("jurisdiction", sa.String(2), nullable=False),
    sa.Column("section", sa.Text, nullable=False),
    sa.Column("heading", sa.Text, nullable=False),
    sa.Column("part", sa.Text, nullable=False),
    sa.Column("page_start", sa.Integer, nullable=False),
    sa.Column("page_end", sa.Integer, nullable=False),
    sa.Column("text", sa.Text, nullable=False),
    sa.Column("tokens", sa.Integer, nullable=False),
    sa.Column("embedding", Vector(settings.embedding_dim), nullable=False),
    # Generated by Postgres, so it is never part of an INSERT
    sa.Column(
        "search",
        TSVECTOR,
        sa.Computed("to_tsvector('english', heading || ' ' || text)", persisted=True),
    ),
)
